# Generated by Django 3.2.5 on 2021-09-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=200)),
                ('Subject', models.CharField(max_length=100)),
                ('Message', models.TextField(max_length=1000)),
            ],
        ),
    ]
